openspeech/urls.py
from django.contrib import admin
from django.urls import path, include
from openspeech.views import initial_page


app_name = 'openspeech'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', initial_page, name='initial_page'),
    
    # registering the urls from users_register app
    path('', include('users_register.urls')),
]

users_register/urls.py
from django.contrib import admin
from django.urls import path, re_path
from users_register.views import *
from django.urls import reverse

app_name = 'users_register'

urlpatterns = [
    path('register/', register_page, name='register_page'),
    path('login/', login_page, name='login_page'),
    path('logout/', logout_page, name='logout_page'),
    path('home/<str:user>/', index_page, name='index_page'),
    #path('home/<str:user>/post/<int:post_id>/', post_page, name='post_page'),
]

users_register/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.timezone import now

from django.urls import reverse

class PostData(models.Model):
    CATEGORY_CHOICES = (
    ('Technology', 'Technology'),
    ('Entertainment', 'Entertainment'),
    ('Politics', 'Politics'),
    ('Food', 'Food'))
    
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=100)
    content_body = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    content_type = models.CharField(max_length=100, null = True, choices=CATEGORY_CHOICES)
    

    def __str__(self):
        return self.title
    
    def body_snippet(self):
        return self.content_body[:150] + '.........'

users_register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    
    class Meta:
        model = User
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            }
        fields = ['username', 'email', 'first_name', 'last_name', 'password1',
                  'password2']
        

openspeech/views.py
from django.shortcuts import render
from django.http import HttpResponse

def initial_page(request):
    return render(request, 'openspeech/initial_page.html')

users_register/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from .forms import RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import PostData


def register_page(request):
    if request.user.is_authenticated:
        user = request.user
        return redirect('users_register:index_page', user)
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users_register:login_page')
        else:
            return render(request, 'users_register/register_page.html', {'form': form})
    else:
        form = RegisterForm()
    return render(request, 'users_register/register_page.html', {'form': form})


def login_page(request):   
    if request.user.is_authenticated:
        user = request.user
        return redirect('users_register:index_page', user)
    if request.method == 'POST':
        form = AuthenticationForm(data= request.POST)
        if form.is_valid():
            user = form.get_user()
            #user = authenticate(request, username = user_data.username, password = user_data.password)
            if user is not None:
                login(request, user)
                user = request.user
                #user_path = user.first_name.replace(" ","")                
                #print(user_path)
                return redirect('users_register:index_page',user)
            else:
                return HttpResponse('Invalid Credentials')
        else:
            return render(request, 'users_register/login_page.html', {'form': form})
    else:
        form = AuthenticationForm()
    return render(request, 'users_register/login_page.html', {'form': form})


def logout_page(request):
    logout(request)
    return redirect("initial_page")


@login_required(login_url='users_register:login_page')
def index_page(request, **kwargs):
    user_name = kwargs['user']
    user = User.objects.get(username=user_name)
    user_name = user.first_name
    
    data = PostData.objects.all().order_by('-date_posted')
        
    content ={
        'user_name': user_name,
        'data': data,
    }
    
    return render(request, "users_register/index_page.html", content)


def post_page(request, **kwargs):
    post__id = kwargs['post_id']
    data = PostData.objects.get(id=post__id)
    
    content ={
        data: data,
    }
    
    return render(request, "users_register/post_page.html", content)

openspeech/templates/openspeech/base_page.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


<body>
    <!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>

<head class="header">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{% block site_name %}{% endblock %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item col-sm-2">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item col-sm-2">
            <a class="nav-link" href="#">Friends</a>
          </li>
          <li class="nav-item col-sm-2">
            <a class="nav-link" href="#">Photos</a>
          </li>
          {% block user_register %}
          {% endblock %}
        </ul>
            <form class="d-flex flex-row-reverse" role="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            <input class="col-sm-4" type="search" placeholder="Search" aria-label="Search" type="submit">
            </form>
      </div>
    </div>
  </nav>
</head>

<body>
  


{% block content %}
{% endblock %}

</body>
<footer class="container-fluid">
  <p>Footer Text</p>
</footer>
</html>

openspeech/templates/openspeech/initial_page.html
{% extends 'openspeech/base_page.html' %}

{% block title %}
<title>Open Speech</title>
{% endblock title %}

{% block site_name %}
Blogger's Place
{% endblock %}

{% block user_register %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Create User
    </a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href={% url 'users_register:login_page'%}>Login</a></li>
        <li><a class="dropdown-item" href={% url 'users_register:register_page'%}>Register</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Continue as Guest</a></li>
    </ul>
    </li>

{% endblock %}

users_register/templates/users_register/index_page.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

{% extends 'openspeech/base_page.html' %}

{% block title %}
<title>Home</title>
{% endblock title %}

{% block site_name %}
{{user_name}}'s Blog
{% endblock site_name %}


{% block user_register %}
<li class="nav-item col-sm-2">
    <a class="nav-link" href={% url 'users_register:logout_page'%}>Logout</a>
</li>
{% endblock user_register %}

{% block content %}

<div class="container-fluid">
  <div class="col-sm-9">
    <h4><small>RECENT POSTS</small></h4>
    <hr>
    
    {% csrf_token %}
      {% for value in data %}
    
      <div class="row">
        <div class="container-fluid bg-3">
          <div class="col-sm-2 text-center">
            <img src="bandmember.jpg" class="img-circle" height="65" width="65" alt="Avatar">
          </div>

          <div class="col-sm-10">
            <h2>{{value.title}}</h2>
            <h5>
              <span class="glyphicon glyphicon-time"></span>
               Post by {{value.user_id.first_name}} {{value.user_id.last_name}}, {{value.date_posted}}.</h5>
            <h5>
              <span class="label label-info">{{value.content_type}}</span>
            </h5><br>
            <p>{{value.body_snippet}}</p>
            <br><br>
          </div>
        </div>
      {% endfor %}


    </div>

  </div>
</div>
{% endblock %}  

users_register/templates/users_register/login_page.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'users_register:register_page' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

users_register/templates/users_register/post_page.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

{% extends 'openspeech/base_page.html' %}

{% block title %}
<title>home</title>
{% endblock title %}

{% block site_name %}
{{user_id}}'s Blog
{% endblock site_name %}


{% block user_register %}
<li class="nav-item col-sm-2">
    <a class="nav-link" href={% url 'users_register:logout_page'%}>Logout</a>
</li>
{% endblock user_register %}

{% block content %}

<div class="container-fluid">
  <div class="col-sm-9">
    <h4><small>RECENT POSTS</small></h4>
    <hr>
    
    {% csrf_token %}
    
      <div class="row">
        <div class="container-fluid bg-3">
          <div class="col-sm-2 text-center">
            <img src="bandmember.jpg" class="img-circle" height="65" width="65" alt="Avatar">
          </div>

          <div class="col-sm-10">
            <h2>{{data.title}}</h2>
            <h5><span class="glyphicon glyphicon-time"></span> Post by {{data.user_id.first_name}} {{data.user_id.last_name}}, {{data.date_posted}}.</h5>
            <h5><span class="label label-info">{{data.content_type}}</span> <span class="label label-info">not declared</span></h5><br>
            <p>{{data.content_body}}</p>
            <br><br>
          </div>
        </div>


      
    </div>

  </div>
</div>
{% endblock %}  

users_register/templates/users_register/register_page.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
                            {{form.email}}
						</div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-id-badge"></i></span>
							</div>
                            {{form.first_name}}
						</div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-id-badge"></i></span>
							</div>
                            {{form.last_name}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'users_register:login_page' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
var form_fields = document.getElementsByTagName('input')
form_fields[4].placeholder='Enter password...';
form_fields[5].placeholder='Re-enter Password...';


for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>
</body>
</html>